raw_data_config:
  url_data: https://archive.ics.uci.edu/ml/machine-learning-databases/00212/vertebral_column_data.zip
  filename_data: column_3C_weka.arff
  raw_data_csv: data/raw/data.csv
  #model_var: ['pelvic_incidence','pelvic_tilt','lumbar_lordosis_angle','sacral_slope','pelvic_radius','degree_spondylolisthesis','class']
  train_test_split_ratio: 0.2
  target: class
  random_state: 111
  #new_train_data_csv: 

processed_data_config:
  train_data_csv: data/processed/VC_train.csv
  test_data_csv:  data/processed/VC_test.csv

model_choice:
  # random_forest or knn
  model: 'knn'
  # model: 'random_forest'

random_forest: 
  max_depth: 15
  n_estimators: 50

knn: 
  n_neighbors: 30

mlflow_global_config:
  artifacts_dir: artifacts
  experiment_name: model_VC
  registered_model_name: VC_model
  remote_server_uri: http://127.0.0.1:1234

mlflow_random_forest_config:
  run_name: random_forest
  

mlflow_knn_config:
  run_name: knn
  
model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html
