name: PyTest

on : push

jobs:
  test:
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Execute tests
        run: pytest tests